apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: current-connect-cluster
spec:
  version: 3.4.0
  replicas: 1
  bootstrapServers: 'current-cluster-kafka-bootstrap:9093'
  tls:
    trustedCertificates:
      - secretName: current-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
