apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: current-topic
  labels:
    strimzi.io/cluster: current-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
