apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: current-source-connector
  labels:
    strimzi.io/cluster: current-connect-cluster
spec:
  class: org.apache.kafka.connect.file.FileStreamSourceConnector
  tasksMax: 1
  config:
    file: /opt/kafka/LICENSE
    topic: my-topic
