# To install already provided version of operator we need
# a test namespace and related og and sub resources in that ns.

apiVersion: v1
kind: Namespace
metadata:
  name: kuttl-test
---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: global-operators
  namespace: kuttl-test
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rabbitmq-cluster-operator.kuttl-test: ""
  name: rabbitmq-cluster-operator
  namespace: kuttl-test
spec:
  channel: stable
  installPlanApproval: Manual
  name: rabbitmq-cluster-operator
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: rabbitmq-cluster-operator.v2.0.0 # change in case of difference
  config:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 300m
        memory: 1Gi
