apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rabbitmq-cluster-operator.kuttl-test: ""
  name: rabbitmq-cluster-operator
  namespace: kuttl-test
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rabbitmq-cluster-operator
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: rabbitmq-cluster-operator.v2.8.0 # change in case of difference
  config:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 300m
        memory: 1Gi
