apiVersion: kuttl.dev/v1beta1
kind: TestStep
scripts:
  - command: installplan_name=$(kubectl get installplans -n kuttl-test-postgres -o jsonpath='{.items[0].metadata.name}') && kubectl patch installplan $installplan_name -n kuttl-test-postgres --type merge -p '{"spec":{"approved":true}}'
