apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgresql
  namespace: kuttl-test-postgres
spec:
  channel: v5
  installPlanApproval: Automatic
  name: postgresql
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: postgresoperator.v5.5.1 # change in case of difference
